language: node_js
node_js:
  - '10'
before_install:
  - npm i npm-cli-login -g
  - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
  - npm who
install:
  - rm -rf node_modules
  - rm -rf tmp
  - npm install
script:
  - ./ci/build.js
  - ./ci/test.js
after_success:
  - ./ci/travis/publish.js
env:
  secure: "uvPhE9eoYfsqaS+odet1pBUZYh7kh8TIcRMz7Tupgka+JQL68G4goBT6xFrKYc60M9I4BuDbk3MgZqHYvmyOBC+sbX16Y3fntlztX7F5uLAaif022UwKXc6C68EksX491M2nRhAHcU1IoHzW1wRrRDtcU12rnnahVQ/ATM/jrZ0A9tSHhZQj6MWZpCmRsTrYtjr/xj+vXPrsjcRfXeb9huaphwEkmHOVmIf40fGDlhDJcnkgiTUPgyM3E51teNP2oWLifFceq+KJnwDin4SSwP/mCx/VCpeuNCSsyORFjfkmjxYkkTSSMJeWbbxRjDByU9+Cp1QaGh6yW5v+gkN5p1wvOuOzieegKvTROx8RTG9O8aXbTx19+GQQnBWx/U2uzngmWzdnUQQOKrLHTTwwSoFA+OrKFese1Iv5W2EausVDOtHVu2Fgi6PcubRT8eItMvTiyte6KuckRAIRnN+R4kHwcP9pHvfFV7S2r9YHcv6gJ4FUvnFHmq1x4OYox1Z2yt+LW4PICv+Cr7vobUbt2tKp7alYc8HwXbFVDQtgjI3ulC2Toneo/RCsRSbUQdzugu0p9Yu9sl9vDvVoyL9EmSjepfaPE/CUSY84d+86ERP2sO6AZDDTdvvL1TF/G8I7IzWp19r/5RmwQb/HjYzH5je4SNPopwhxlLUhhh66KuY="
