language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "PaVkpKqT2evKNijBiaGxt78ew0xzDXyM+tW/OnQqobngw4IDN2x/RscgK0TFNm+BViZU7/jNHVKhPHF1auH6Xn/uk1Z/jAn2lkJX92Fd0+306KQ/kJ8tQQuxLJ8+nTfxNlr67/JeZMahxvSnos1Q535HSMwqXuuxUrLiaymHJfwRfUNUtP6jNdGb3pKMWpW8PODd1yYiBC23v+VbfefcJGWPQSWqPggeJ9xcYzL3CFusoq0/N3NIQGE+MgmyQrQQY94hwzLWZkTjXAUp6WuxtiFtufHErRrASfHvWiEzlVu+Zn6BI73WDSXcTfv8zGiH4kTiTrsHR6lbsDgVxIfBQhzGSEweV0yh6HkyyVaysqBh0MPgYOXKZcisim4xYiSTZ462BXqrDrb+0HcYvX6MwNYfdc2PBtG3AfZ1UIbSw+ZWtaRXMk869NWYLi7E2a5lxO6rkvGabFFcJkOBA3o/r4Zt5s1LLhesuJBIDptsnMUTK9yLO+LafR03x54rtwelKCz3iu3xKKLvEHmkfulaJMjWdvln8qtOKxfqtDTPh66DFBWqArRSEhfhBJbKM4MizNXB6Fg1S48ZM8OEFuScbXXnx3MEA3+htYuaXiHYHRsbzw9EHvxEMZDlgDz6+iAT1pl6LwXvpRgrj7Xhvl38uYmJUUNbwBoJu1r3R0hRc0s="
env:
  secure: "uvPhE9eoYfsqaS+odet1pBUZYh7kh8TIcRMz7Tupgka+JQL68G4goBT6xFrKYc60M9I4BuDbk3MgZqHYvmyOBC+sbX16Y3fntlztX7F5uLAaif022UwKXc6C68EksX491M2nRhAHcU1IoHzW1wRrRDtcU12rnnahVQ/ATM/jrZ0A9tSHhZQj6MWZpCmRsTrYtjr/xj+vXPrsjcRfXeb9huaphwEkmHOVmIf40fGDlhDJcnkgiTUPgyM3E51teNP2oWLifFceq+KJnwDin4SSwP/mCx/VCpeuNCSsyORFjfkmjxYkkTSSMJeWbbxRjDByU9+Cp1QaGh6yW5v+gkN5p1wvOuOzieegKvTROx8RTG9O8aXbTx19+GQQnBWx/U2uzngmWzdnUQQOKrLHTTwwSoFA+OrKFese1Iv5W2EausVDOtHVu2Fgi6PcubRT8eItMvTiyte6KuckRAIRnN+R4kHwcP9pHvfFV7S2r9YHcv6gJ4FUvnFHmq1x4OYox1Z2yt+LW4PICv+Cr7vobUbt2tKp7alYc8HwXbFVDQtgjI3ulC2Toneo/RCsRSbUQdzugu0p9Yu9sl9vDvVoyL9EmSjepfaPE/CUSY84d+86ERP2sO6AZDDTdvvL1TF/G8I7IzWp19r/5RmwQb/HjYzH5je4SNPopwhxlLUhhh66KuY="
